locales:
  mpu:
    name: Makuráp Keyboards
    description: >-
      Mobile OS keyboards for the Makuráp language from the Divvun group
      at UiT.
  en:
    name: Makuráp Keyboards
    description: >-
      Mobile OS keyboards for the Makuráp language from the Divvun group
      at UiT.
  nb:
    name: Makuráp tastatur
    description: Mobiltastatur for Makuráp fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
